layout_spectrum: 0.7413562415167689
typography_spectrum: 0.7777031494770199
color:
  brandStrength: 0.8400198749732226
  lightness: 0.6230463415849954
  saturation: 0.4911491081584245
  rhythmicContrast: 0.3290312478784472
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
name: Jabriel Boyce
title: Jabriel Shore
description: Storyteller
