layout_spectrum: 0.8254717935342342
typography_spectrum: 0.43088914663530886
color:
  brandStrength: 0.9517821783665568
  lightness: 0.4769692160189152
  saturation: 0.836735368706286
  rhythmicContrast: 0.3903805115260184
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Jabriel Boyce
title: from the desk of Jabriel Shore
