typography_spectrum: 0.5794872790575027
color:
  saturation: 0.9158385428600013
  brandStrength: 0.15929803694598377
  lightness: 0.09500488545745611
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
  rhythmicContrast: 0.4864571944344789
layout_spectrum: 0.4785177
name: Jabriel Boyce
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bcbeb1fc-e39c-4c8c-bd66-2124462da707.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Gabe B Shore
description: "story-tailor \_/ \_keeping witness \_/ \_empower others"
